### PR TITLE
Add support for open source MonoMac and GtkSharp

### PR DESCRIPTION
**Pull request by dlech**
I don't think there is a way to get nuget to detect this correctly, but at least you can make it work by manually editing your .csproj.

### CODE REVIEW

**Comment by paulcbetts** [comment]
I'm mostly into this, a few things:

1. Can you get rid of the extra SLN file and just put it into Splat-XamarinStudio.sln
1. Can you ditch MoreSplat and make a Splat.GtkPlus and Splat.MonoMac.OSS?

**Comment by dlech** [comment]
I actually didn't mean to add all of these commits to this pull request, but I'm glad you are liking it.

1. Yes, I can do that.
2. I'm still figuring out how nuget works and have realized that this is the way to go. The GTK/GDK stuff actually only works with GTK#3, so I will name it Splat.GtkSharp3 instead.

**Comment by dlech** [comment]
I've straightened things out a bit, so now we have 3 new Nuget packages: Splat.MonoMac.OSS, Splat.GtkSharp and Splat.GtkSharp3. I added an Extra/ subdirectory under Splat/bin so that they won't interfere with the existing nuspec.

**Comment by dlech** [comment]
I should mention that in order to get the gtk-sharp-3 assemblies, you will have to do a little work. See <http://stackoverflow.com/a/29184364/1976323>.

**Pull request closed without merging**
