### PR TITLE
Logging Rewrite

### PR DESCRIPTION
**Pull request by kentcb**
Opening this PR super early so people can track progress/provide input.
- [ ] platform-specific log sink implementations that do the right thing (see #58)
- [ ] `IsXxxEnabled` support (will supersede #110)
- [ ] allocation-free logging
- [ ] up to 10 arguments before a `params` overload takes over (at which point it's no longer allocation-free)
- [ ] log name support (defaults to calling type name)

### CODE REVIEW

**Comment by Belorus** [comment]
@kentcb Hey Kent. 
Do you think https://github.com/Belorus/XLog follows the points that u've outlined ? 
I want to try reimplementing logger in RUI taking some ideas from XLog

**Comment by ghuntley** [comment]
Check out https://github.com/kentcb/Genesis.logging for insights into Kent's style.

**Comment by kentcb** [comment]
@Belorus It seems like XLog does a great job with respect to minimizing allocs:

> Logging one message to file produces 1 memory allocation

I'd be interested to hear what this one alloc is caused by. Is it the caller's `string` alloc? Or is it because the message is being written to file? i.e. if the message went nowhere (logging was essentially disabled) would it be alloc-free?

My understanding of string interpolation is admittedly quite limited. However, I intuit that it allocs _and_ formats proactively (and is culture aware!), which would lead to poor performance. For example:

```C#
logger.Debug($"Hello, {world}!");
```

Here, a `FormattableString` would be allocated _and_ formatting would take place so that the `world` variable is substituted into the string. If the log message is thrown away (because e.g. it's DEBUG and we've set the threshold to INFO) then all that work was done for nothing.

If, on the other hand, we use the traditional approach:

```C#
logger.Debug("Hello, {0}!", world);
```

Now the logging infrastructure can check whether debugging is even enabled before bothering to format the string.

By using poor-man's variadic templates we can generate generic methods so that boxing does not take place. See [this T4 template](https://github.com/kentcb/Genesis.Logging/blob/master/Src/Genesis.Logging/LoggerExtensions.tt) and [the resultant output](https://github.com/kentcb/Genesis.Logging/blob/master/Src/Genesis.Logging/LoggerExtensions.cs).

**Comment by glennawatson** [comment]
This has been added by @cabauman now. Sorry @kentcb  this took so long.

**Pull request closed without merging**
