### PR TITLE
housekeeping: upgrade to vs2017 project format, drop old platforms, make netstandard20 work

### PR DESCRIPTION
**Pull request by ghuntley**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

housekeeping/features/**breaking change** (dropping wpa81)

**What is the current behavior? (You can also link to an open issue here)**

#153 - use lots of old style projects
#152 & #158 -  type conflicts with netstandard

**What is the new behavior (if this is a feature change)?**

- use VS2017 projects
- 🔥 some of the #ifdefs to match RxUI

**Does this PR introduce a breaking change?**

Yes, this will be `splat v3.0.0`

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/paulcbetts/splat/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features) - I can try and add tests, but there's currently no infrastructure
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

Splat currently includes some winforms/wpf specific things as part of the net45 package, it might be worth pulling these out as we did for ReactiveUI to make it easier to use in server side usages for example or improving compatibility for consumption w/visual studio for mac.

### CODE REVIEW

**Comment by ghuntley** [comment]
TODO:
- [x] Configure appveyor CI webhook
- [ ] Re-encrypt secrets in appveyor.yml as they have expired
- [ ] Test consumption of `splat` v3.0 in VS4MAC into a NET45 project - does it bring in `WindowsForms` or `WindowsPresentatiomBase`?

**Comment by ghuntley** [comment]
Testing VS4MAC consumption will need to be tested

image

These references may cause it to explode when installed into a `net45` library

**Comment by olevett** [comment]
Latest commits cover #152/#158, I grabbed what @paulanthonymorris did (thanks for picking it up 👍 ) and then applied that on top of the csproj changes.

**Comment by MKuckert** [comment]
I resolved the conflicts with the `Splat/Android/Bitmaps.cs`-file in our fork: https://github.com/SALT-AND-PEPPER/splat/commit/dbc51d0b02bbea9a85525de43e98ce4e75b9aeb7

The AppVeyor failures look pretty strange. As far as I can tell it looks like NuGet crashed?!

**Comment by olevett** [comment]
Potential pain point with this is pulling out a Splat.Wpf platform, to prevent breaking vs4mac when installing net45 targets.

This is a fairly minor change in the grand scheme of things, but would be good to get some feedback from people installing on vs4mac/into Xamarin Mac projects.

**Comment by verybadcat** [comment]
As a consumer of this, I would love to be able to use with .netstandard.

**Pull request merged**
