### PR TITLE
housekeeping: Stop the Nlog logger creating a log table every Write

### PR DESCRIPTION
**Pull request by glennawatson**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
housekeeping

**What is the current behavior? (You can also link to an open issue here)**
That every time a Write() call is made it'll generate a new instance of the Splat Log Level -> NLog Log Level. Also those entries are Tuple's which are heap alloc.

**What is the new behavior (if this is a feature change)?**
Keep them in a static variable which initializes them once. Also use KeyValuePair which is a struct so is more efficient in this use case.

**What might this PR break?**
Might cause issues for @dpvreony with his most recent PR.

### CODE REVIEW

**Comment by snakefoot** [comment]
@glennawatson &  @dpvreony  Possible that you could change the array into a static Dictionary. Then you could do the lookup faster and without doing delegate-capture?

**Comment by glennawatson** [comment]
static dictionary would only be faster for sufficiently large N, due to cache coherence etc. At 5 elements it's debate if it is faster, also in the case of Serilog I have to iterate over the elements as well, and iterating over a dictionary usually is slower due to bucketing etc.

I would personally potentially also go for a ImmutableDictionary for thread safety.

**Comment by snakefoot** [comment]
Why iterate when you can do TryGetValue?


Sent from my Sony Xperia


---- Glenn Watson wrote ----


static dictionary would only be faster for sufficiently large N, due to cache coherence etc. At 5 elements it's debate if it is faster, also in the case of Serilog I have to iterate over the elements as well, and iterating over a dictionary usually is slower due to bucketing etc.

I would personally potentially also go for a ImmutableDictionary for thread safety.

**Comment by snakefoot** [comment]
Created #258 for you

**Pull request merged**
