### PR TITLE
housekeeping: add flags for making visual studio preview and maui optional

### LINKED ISSUE #797: housekeeping: vs2022 go live CI changes
**Is your feature request related to a problem? Please describe.**
When VIsual Studio 2022 goes RTM rather than delete the current update block out the CI action I was thinking

* put a variable at the top of the build (or hide away in the repo settings)
* put a run condition on the VS2022 update task
* rename it to "Use Visual Studio Preview"

**Describe the solution you'd like**
as above

**Describe alternatives you've considered**
deleting it, remarking it

**Describe suggestions on how to achieve the feature**

**Additional context**
i suggested variable rather than repo setting due to the security on the repo settings, and it can be done on a long running branch etc without affecting main

### PR DESCRIPTION
**Pull request by dpvreony**
**What kind of change does this PR introduce?**
CI change
closes #797 

**What is the current behavior?**
Always opt for running vs2022 preview and maui check

**What is the new behavior?**
allows moving to stable\preview versions of both (once maui in vs properly)

**What might this PR break?**
n/a

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by glennawatson — APPROVED** [review]

**Comment by glennawatson** [comment]
We could possibly just add a global "secret" as a environment variable, and make more consistent use of our github actions.

Also might be worth adopting this at some point https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

**Comment by glennawatson** [comment]
Guess we need another flag for install preview now as well.

**Comment by dpvreony** [comment]
will look at reusable. could then put it in https://github.com/reactiveui/.github to share between the repos that need it? get it working first :)

as for flags as you like

**Comment by dpvreony** [comment]
status check doesn't seem to like the change to a workflow. is it a simple tweak in the settings? if so and happy to proceed based on the ci yml i'll do the release yml

**Comment by glennawatson** [comment]
Seems the status name has been changed. To build build build.

**Comment by glennawatson** [comment]
I've created https://github.com/reactiveui/actions-common

You have access to that repo

Might be a better location for this script

**Comment by dpvreony** [comment]
https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow suggests it needs to be in .github/workflows

will try tagging to main

**Comment by dpvreony** [comment]
the question of names in each of the bits "build build build"
ci (in the splat yml) common build (in the workflow)

**Comment by glennawatson** [comment]
Yeah I can change it to reference build / build / build, I guess that's a valid workaround although a bit ugly.

**Comment by glennawatson** [comment]
Once that is done I'll get some help updating all the other repos to use this script where practical. 

RxUI will likely be the tricky one due to multiple sln, might need to move those additional sln into different folder just to make our lives easier.

**Pull request merged**
