### PR TITLE
Fix For Avalonia Router randomly stops showing views on navigation.

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What kind of change does this PR introduce?**

Fix for #1027 

**What is the current behavior?**

Avalonia PageTransitions has an issue with static Page transitions

**What is the new behavior?**

An 125ms Opacity animation has been created using reactive methods and bindings to replace the Avalonia Animation

**What might this PR break?**

A new class has been created so no existing code should be affected.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
Added TransitioningContentControlReactiveUI as a patch for Avalonia's TransitioningContentControl the PageTransitions have an issue after x transitions. The replacement has a fixed Opacity animation.

### CODE REVIEW

**Comment by ChrisPulman** [comment]
The animation issue is a known bug in Avalonia 11 [Issue 12333](https://github.com/AvaloniaUI/Avalonia/issues/12333)

**Comment by glennawatson** [comment]
Remove ReactiveUI.Avalonia, going to cause confusion. I'll unregister it on nuget.org

**Comment by glennawatson** [comment]
I've unlisted all those RxUI.Avalonia packages.

Should be ONLY splat.* going forward.

**Comment by glennawatson** [comment]
I guess also the naming scheme should be `Splat.<DIContainer>.Avalonia` just to make it clear its not a override plugin 

Any fixes for avalonia bugs need to go to avalonia, eg we aren't fixing UI bugs here in Splat so closing this PR and would be more appropriate for #1027 to be handled by them.

**Pull request closed without merging**
