### PR TITLE
Update solution to use net 8.0

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What kind of change does this PR introduce?**

Feature - Add Net 8.0

**What is the current behavior?**

Targets up to net 7.0

**What is the new behavior?**

Targets up to net 8.0

**What might this PR break?**

VS2022 Preview will need to be used until the release comes out with net 8.0 support

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by dpvreony — COMMENTED** [review]
can remove a chunk of the #if blocks by using the following workaround. will see if I can get time later this week as traveling

```
    /// <summary>
    /// Allows capturing of the expressions passed to a method.
    /// Shims for CallerArgumentExpressionAttribute to provide compatability with NET48
    /// Taken from: https://weblogs.asp.net/dixin/csharp-10-new-feature-callerargumentexpression-argument-check-and-more on 20230904.
    /// </summary>
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    internal sealed class CallerArgumentExpressionAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallerArgumentExpressionAttribute"/> class.
        /// </summary>
        /// <param name="parameterName">The name of the targeted parameter.</param>
        public CallerArgumentExpressionAttribute(string parameterName) => ParameterName = parameterName;

        /// <summary>
        /// Gets the target parameter name of the <c>CallerArgumentExpression</c>.
        /// </summary>
        /// <returns>
        /// The name of the targeted parameter of the <c>CallerArgumentExpression</c>.
        /// </returns>
        public string ParameterName { get; }
    }
```

```
    /// <summary>
    /// Shims for ArgumentNullException to provide compatability with NET48.
    /// </summary>
    internal static class ArgumentNullException
    {
        /// <summary>Throws an <see cref="T:System.ArgumentNullException" /> if <paramref name="argument" /> is <see langword="null" />.</summary>
        /// <param name="argument">The reference type argument to validate as non-null.</param>
        /// <param name="paramName">The name of the parameter with which <paramref name="argument" /> corresponds.</param>
        /// <exception cref="T:System.ArgumentNullException">
        /// <paramref name="argument" /> is <see langword="null" />.</exception>
        public static void ThrowIfNull(object? argument, [CallerArgumentExpression("argument")] string? paramName = null)
        {
            if (argument != null)
            {
                return;
            }

            throw new global::System.ArgumentNullException(paramName);
        }
    }
```

**Comment by ChrisPulman** [comment]
@dpvreony thank you, I am also travelling in the UK this week, then possibly in India next week or the week after for 2 weeks.

**Comment by glennawatson** [comment]
I guess the disadvantage of the helper method is the inbuilt one gives a clean stack, while this one adds one more layer to the stack call.

**Comment by ChrisPulman** [comment]
> I guess the disadvantage of the helper method is the inbuilt one gives a clean stack, while this one adds one more layer to the stack call.

The Api will also have two helpers one per framework difference, in some cases 3 variances, as we will still need to put the #buildFramework elements into the helpers. Personally, I am ok with the #if #else option hence I choose to spend the time to fix them, I don't see us having to change those sections of code again so it's not really a maintenance issue, but which is more performant should be the way we go.

**Comment by glennawatson** [comment]
Stick with the #if for the moment. 

When netstandard disappears we can strip them out.

**Review by glennawatson — APPROVED** [review]

**Pull request merged**
