### PR TITLE
Update Avalonia - ReactiveUI.Avalonia.* to Splat.Avalonia.*

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What kind of change does this PR introduce?**

Update

**What is the current behavior?**

ReactiveUI.Avalonia does not follow solution names of Splat.

**What is the new behavior?**

Rename ReactiveUI.Avalonia.* to Splat.Avalonia.*
Remove ReactiveUi.Avalonia
Rename Avalonia Tests

**What might this PR break?**

Packages now have different names, ReactiveUi.Avalonia no longer exists.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by dpvreony** [comment]
when it's done can someone with nuget access deprecate the old package and mark this as the replacement?

**Review by dpvreony — DISMISSED** [review]

**Review by dpvreony — DISMISSED** [review]
the folder names could do with being tweaked

**Comment by ChrisPulman** [comment]
> when it's released can someone with nuget access deprecate the old package and mark this as the replacement?

I understand the original packages have already been unlisted.

**Comment by ChrisPulman** [comment]
> the folder names could do with being tweaked

I will update the folder names in the morning, thank you.

**Review by glennawatson — APPROVED** [review]

**Pull request merged**
